baseURL = 'nekofiore.net/'
languageCode = 'en-us'
title = 'nekofiore'

theme = "base"

[taxonomies]
  category = "categories"
  tag = "tags"
  volume = "volumes"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
  
[markup.goldmark.renderer]
  unsafe = true
