baseURL = 'https://nekofiore.github.io/'
languageCode = 'en-us'
title = 'nekofiore'

theme = "base"

[taxonomies]
  category = "categories"
  tag = "tags"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
